
repos:
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files
    - repo: local
      hooks:
        - id: pylint-app
          name: pylint-app
          entry: pipenv run pylint app/
          language: system
          always_run: true
          pass_filenames: false
        - id: pylint-load
          name: pylint-load
          entry: pipenv run pylint load.py
          language: system
          always_run: true
          pass_filenames: false
        - id: pipenv to requirements
          name: pipenv to requirements
          entry: pipenv run pipenv_to_requirements
          language: system
          always_run: true
          pass_filenames: false